dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel_3.1.0-linux-x86_64.deb
  - sha256sum -c tools/bazel_3.1.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_3.1.0-linux-x86_64.deb

script:
  - bazel build --sandbox_debug //lexer:tokenizer
