cc_library(
    name='lexer',
    srcs=[
        'lexer.cc',
    ],
    hdrs=[
        'lexer.h',
    ],
    deps=[
        '@com_github_google_glog//:glog',
    ],
)


cc_library(
    name='token',
    srcs=[
        'token.cc',
    ],
    hdrs=[
        'token.h',
    ],
    deps=[
        '@com_github_google_glog//:glog',
    ],
)
