package(default_visibility = ['//visibility:public'])

cc_library(
  name='fd-closer',
  srcs=[
    'fd-closer.cc',
  ],
  hdrs=[
    'fd-closer.h',
  ],
  deps=[
    '@com_github_google_glog//:glog',
  ],
)
